del "c:\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\int\x86\*.obj"

ECHO OFF
cls
ECHO _________________________
ECHO Compiling...
ECHO _________________________

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64\ -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\TrapController.cu" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\TrapController.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\TrapControllerHandler.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\TrapControllerHandler.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\AtomSim.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\AtomSim.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\AWGController.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\AWGController.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\CameraServer.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\CameraServer.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\Console.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Console.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\main.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\main.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\rearrange2d.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\rearrange2d.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\sb5_file.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\sb5_file.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\spcm_lib_card.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_lib_card.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\spcm_lib_data.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_lib_data.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\spcm_ostools_win.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_ostools_win.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\Trap.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Trap.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\Waveform.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Waveform.obj"

nvcc.exe -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -m 64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I..\include\ -I..\..\cuda_lib\include -L..\..\cuda_lib\lib\x64 -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp -I"..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\include" "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\src\WaveTable.cpp" -c -o  "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\WaveTable.obj"

ECHO _________________________
ECHO LINKING...
ECHO _________________________

nvcc.exe -odir "c:\users\bernien lab\documents\bernien_lab\2d_trap_controller\new_code\int\x86" -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64" -L  "..\..\..\..\..\users\bernien lab\documents\bernien_lab\2d_trap_controller\c_header_win" -lspcm_win64_msvcpp "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\WaveTable.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Waveform.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Trap.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_ostools_win.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_lib_data.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\spcm_lib_card.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\sb5_file.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\rearrange2d.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\main.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\Console.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\CameraServer.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\AWGController.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\TrapControllerHandler.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\TrapController.obj" "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\AtomSim.obj"

ECHO FINISHED!

cd "C:\Users\Bernien Lab\Documents\bernien_lab\2d_Trap_Controller\New_Code\int\x86\"
a.exe
del a.exe
del a.exp
del a.lib
cd "C:\users\bernien lab\documents\bernien_lab\2d_Trap_Controller\new_code\scripts"
